#!/bin/bash

# Check if the file 'iacta' exists
if [ -f "iacta" ]; then
	# Get the last line of the file and store it in a variable
	last_line=$(tail -n 1 iacta)
	
	# Append the last line to the file
	echo "$last_line" >> iacta
	
	echo "Last line duplicated in 'iacta'"
else
	echo "File 'iacta' does not exist."
fi
