#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID.
# It displays "To infinity and beyond" indefinitely.
# It displays "I hate the kill command" when receiving a SIGTERM signal.
# It displays "Y U no love me?!" when receiving a SIGINT signal.
# It deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

function love() {
    rm /var/run/holbertonscript.pid
    exit
}

trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT

echo $$ >> /var/run/holbertonscript.pid
while [ true ]; do
    echo To infinity and beyond;
done
