#!/usr/bin/env bash

if [[ "$1" == "start" ]]; then
    while true; do
        echo "I am alive!" >> /tmp/my_process
        sleep 2
    done &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
elif [[ "$1" == "stop" ]]; then
    kill $(cat /var/run/my_process.pid)
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [[ "$1" == "restart" ]]; then
    kill $(cat /var/run/my_process.pid)
    rm /var/run/my_process.pid
    while true; do
        echo "I am alive!" >> /tmp/my_process
        sleep 2
    done &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
