#!/usr/bin/env bash

# Set the server IP or hostname
server="100.25.19.204"

# Set the path to your SSH private key
private_key="/root/school"

# SSH connection using the specified private key and user ubuntu
ssh -i SHA256:wUdbX61VqFFvqQgYNM6ZVzxVAtSEzC8F2Kftte5tmqg ubuntu@d6226201127f
